// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPLvjgm4Uao0id03IH3-LP0JsWzaQc_M',
    appId: '1:1034250753702:web:d7a64737c61b7d7c160667',
    messagingSenderId: '1034250753702',
    projectId: 'my-map-unisell-37de5',
    authDomain: 'my-map-unisell-37de5.firebaseapp.com',
    storageBucket: 'my-map-unisell-37de5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcctr22aHbiArEjCP-sUT4pBhP-Css6DU',
    appId: '1:1034250753702:android:bbe6b3b374e48b22160667',
    messagingSenderId: '1034250753702',
    projectId: 'my-map-unisell-37de5',
    storageBucket: 'my-map-unisell-37de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODkTdwxk-Gg-MZrVuCvlWSUeHN7a_WoI',
    appId: '1:1034250753702:ios:cc61346243137946160667',
    messagingSenderId: '1034250753702',
    projectId: 'my-map-unisell-37de5',
    storageBucket: 'my-map-unisell-37de5.firebasestorage.app',
    iosBundleId: 'com.example.unisell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODkTdwxk-Gg-MZrVuCvlWSUeHN7a_WoI',
    appId: '1:1034250753702:ios:cc61346243137946160667',
    messagingSenderId: '1034250753702',
    projectId: 'my-map-unisell-37de5',
    storageBucket: 'my-map-unisell-37de5.firebasestorage.app',
    iosBundleId: 'com.example.unisell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAPLvjgm4Uao0id03IH3-LP0JsWzaQc_M',
    appId: '1:1034250753702:web:5c4204d55e02b11e160667',
    messagingSenderId: '1034250753702',
    projectId: 'my-map-unisell-37de5',
    authDomain: 'my-map-unisell-37de5.firebaseapp.com',
    storageBucket: 'my-map-unisell-37de5.firebasestorage.app',
  );

}